# -*- coding: utf-8 -*-
"""Statscomb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lAJcUFH2V3OKAix-4g0H8p89nOnjQT9t
"""

import json

with open("282.json", "r", encoding="utf-8") as f:
    matches = json.load(f)

len(matches)

# DANI OLMO ANALYSIS — EURO 2024

import json, os, math
from collections import defaultdict, Counter
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

DATA_FOLDER = "/content"
PLAYER_CANONICAL = "Daniel Olmo Carvajal"
SAVE_FIGURES = True
COMPARE_PLAYERS = 2

def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def safe_get(d, *keys, default=None):
    cur = d
    try:
        for k in keys:
            if cur is None: return default
            if isinstance(k,int): cur = cur[k]
            else: cur = cur.get(k, default) if isinstance(cur, dict) else default
        return cur
    except Exception:
        return default

def ensure_list(x):
    if x is None: return []
    return x if isinstance(x,list) else [x]

with open(os.path.join(DATA_FOLDER,"282.json"), "r", encoding="utf-8") as f:
    matches = json.load(f)

spain_matches = []
for m in matches:
    ht = safe_get(m,"home_team","home_team_name") or safe_get(m,"home_team","name") or ""
    at = safe_get(m,"away_team","away_team_name") or safe_get(m,"away_team","name") or ""
    if (isinstance(ht,str) and ht.lower()=="spain") or (isinstance(at,str) and at.lower()=="spain"):
        spain_matches.append(m)

spain_match_ids = [m["match_id"] for m in spain_matches]
print("Spain matches:", spain_match_ids)

event_files = [fn for fn in os.listdir(DATA_FOLDER)
               if fn.endswith("_event.json") and any(str(mid) in fn for mid in spain_match_ids)]
lineup_files = [fn for fn in os.listdir(DATA_FOLDER)
                if fn.endswith("_lineups.json") and any(str(mid) in fn for mid in spain_match_ids)]

print("Event files:", event_files)
print("Lineup files:", lineup_files)

all_lineups = defaultdict(list)
for lf in lineup_files:
    data = load_json(os.path.join(DATA_FOLDER,lf))
    if isinstance(data,list):
        for entry in data:
            team_name = safe_get(entry,"team_name") or safe_get(entry,"team","name")
            lineup = safe_get(entry,"lineup") or safe_get(entry,"players")
            if team_name and lineup:
                all_lineups[team_name].extend(ensure_list(lineup))
    elif isinstance(data,dict):
        team_name = safe_get(data,"team_name") or safe_get(data,"team","name")
        lineup = safe_get(data,"lineup") or safe_get(data,"players")
        if team_name and lineup: all_lineups[team_name].extend(ensure_list(lineup))

print("Teams found in lineups:", list(all_lineups.keys()))

olmo_played_match_ids = []
for m in spain_matches:
    mid = m["match_id"]
    possible_lineups = [fn for fn in lineup_files if str(mid) in fn]
    found_player = False
    for lf in possible_lineups:
        data = load_json(os.path.join(DATA_FOLDER,lf))
        if isinstance(data,list):
            for entry in data:
                players = safe_get(entry,"lineup") or entry
                for p in ensure_list(players):
                    pname = safe_get(p,"player_name") or safe_get(p,"player","name") or safe_get(p,"name")
                    if pname and PLAYER_CANONICAL.lower()==pname.lower():
                        found_player=True; break
                if found_player: break
        elif isinstance(data,dict):
            for key in ("home_lineup","away_lineup","lineup","players"):
                players = safe_get(data,key)
                if isinstance(players,list):
                    for p in players:
                        pname = safe_get(p,"player_name") or safe_get(p,"player","name") or safe_get(p,"name")
                        if pname and PLAYER_CANONICAL.lower()==pname.lower():
                            found_player=True; break
                if found_player: break
        if found_player:
            olmo_played_match_ids.append(mid)
            break
olmo_played_match_ids = sorted(list(set(olmo_played_match_ids)))
print("Matches Olmo played in:", olmo_played_match_ids)

if not olmo_played_match_ids:
    raise SystemExit("No matches found for Olmo.")

relevant_event_files = [fn for fn in event_files if any(str(mid) in fn for mid in olmo_played_match_ids)]
all_events=[]
for ef in relevant_event_files:
    data = load_json(os.path.join(DATA_FOLDER,ef))
    if isinstance(data,list): all_events.extend(data)
    elif isinstance(data,dict):
        for v in data.values():
            if isinstance(v,list): all_events.extend(v)

events_df = pd.DataFrame(all_events)
print("Total events loaded:", len(events_df))

def event_player_name(e):
    return safe_get(e,"player","name") or safe_get(e,"player_name") or safe_get(e,"player","player_name") or ""

olmo_mask = events_df.apply(lambda r: (event_player_name(r.to_dict()) or "").lower()==PLAYER_CANONICAL.lower(), axis=1)
olmo_events = events_df[olmo_mask].copy()
print("Olmo events:", len(olmo_events))

def extract_xy(e):
    loc = safe_get(e,"location")
    if isinstance(loc,list) and len(loc)>=2: return float(loc[0]),float(loc[1])
    pos = safe_get(e,"position")
    if isinstance(pos,dict) and "x" in pos and "y" in pos: return float(pos["x"]),float(pos["y"])
    shotloc = safe_get(e,"shot","location")
    if isinstance(shotloc,list) and len(shotloc)>=2: return float(shotloc[0]),float(shotloc[1])
    return np.nan,np.nan

if len(olmo_events)>0:
    xs,ys=[],[]
    for i,row in olmo_events.iterrows():
        x,y=extract_xy(row.to_dict())
        xs.append(x); ys.append(y)
    olmo_events["x"]=xs; olmo_events["y"]=ys
    olmo_xy=olmo_events.dropna(subset=["x","y"]).copy()
else:
    olmo_xy=pd.DataFrame(columns=["x","y"])

def safe_type(e): return (safe_get(e,"type","name") or "").lower()
def is_pass(e): return "pass" in safe_type(e)
def is_shot(e): return "shot" in safe_type(e)
def is_dribble(e): return "dribble" in safe_type(e)
def is_pressure(e): return "pressure" in safe_type(e)
def is_ballreceipt(e): return "ball receipt" in safe_type(e)
def is_carry(e): return "carry" in safe_type(e)
def shot_is_goal(e): return (safe_get(e,"shot","outcome","name") or "").lower()=="goal"
def pass_is_assist(e):
    p = safe_get(e,"pass")
    return isinstance(p,dict) and ((p.get("goal_assist") or p.get("assist") or p.get("is_assist")) is True)
def get_shot_xg(e):
    xg = safe_get(e,"shot","statsbomb_xg") or safe_get(e,"shot","xg") or safe_get(e,"xg")
    try: return float(xg) if xg is not None else 0.0
    except: return 0.0

event_types = ["Pass","Shot","Dribble","Pressure","Ball Receipt*","Carry"]
olmo_stats = {
    "total_events": len(olmo_events),
    "Pass": sum(1 for _,r in olmo_events.iterrows() if is_pass(r.to_dict())),
    "Shot": sum(1 for _,r in olmo_events.iterrows() if is_shot(r.to_dict())),
    "Dribble": sum(1 for _,r in olmo_events.iterrows() if is_dribble(r.to_dict())),
    "Pressure": sum(1 for _,r in olmo_events.iterrows() if is_pressure(r.to_dict())),
    "Ball Receipt*": sum(1 for _,r in olmo_events.iterrows() if is_ballreceipt(r.to_dict())),
    "Carry": sum(1 for _,r in olmo_events.iterrows() if is_carry(r.to_dict())),
    "Goals": sum(1 for _,r in olmo_events.iterrows() if shot_is_goal(r.to_dict())),
    "Assists": sum(1 for _,r in olmo_events.iterrows() if pass_is_assist(r.to_dict())),
    "xG": sum(get_shot_xg(r.to_dict()) for _,r in olmo_events.iterrows())
}
print("Olmo stats:", olmo_stats)

spain_players = all_lineups.get("Spain",[])
players_info=[]
for p in spain_players:
    pname = safe_get(p,"player_name") or safe_get(p,"player","name") or safe_get(p,"name")
    pid = safe_get(p,"player_id") or safe_get(p,"player","id")
    players_info.append({"player_id":pid,"player_name":pname})
players_df = pd.DataFrame(players_info).drop_duplicates(subset=["player_id","player_name"])

def compute_player_events(player_name):
    mask = events_df.apply(lambda r: (event_player_name(r.to_dict()) or "").lower()==(player_name or "").lower(),axis=1)
    df = events_df[mask]
    stats = {"player_name":player_name,"total_events":len(df)}
    for etype in event_types:
        if etype=="Pass": stats[etype] = sum(1 for _,r in df.iterrows() if is_pass(r.to_dict()))
        if etype=="Shot": stats[etype] = sum(1 for _,r in df.iterrows() if is_shot(r.to_dict()))
        if etype=="Dribble": stats[etype] = sum(1 for _,r in df.iterrows() if is_dribble(r.to_dict()))
        if etype=="Pressure": stats[etype] = sum(1 for _,r in df.iterrows() if is_pressure(r.to_dict()))
        if etype=="Ball Receipt*": stats[etype] = sum(1 for _,r in df.iterrows() if is_ballreceipt(r.to_dict()))
        if etype=="Carry": stats[etype] = sum(1 for _,r in df.iterrows() if is_carry(r.to_dict()))
    return stats

comp_list = [compute_player_events(PLAYER_CANONICAL)]
other_attackers = players_df[players_df["player_name"].str.lower()!=PLAYER_CANONICAL.lower()]["player_name"].values

for pname in other_attackers[:COMPARE_PLAYERS]:
    comp_list.append(compute_player_events(pname))
comp_df = pd.DataFrame(comp_list)
print("\nComparison (top attackers + Olmo):")
print(comp_df[["player_name","total_events"]+event_types])


def draw_pitch(ax=None,length=120,width=80,lw=1.2,color="black"):
    if ax is None: ax=plt.gca()
    ax.plot([0,0],[0,width],color=color,linewidth=lw)
    ax.plot([0,length],[width,width],color=color,linewidth=lw)
    ax.plot([length,length],[width,0],color=color,linewidth=lw)
    ax.plot([length,0],[0,0],color=color,linewidth=lw)
    ax.plot([length/2,length/2],[0,width],color=color,linewidth=lw)
    return ax

marker_dict = {
    "Pass":"o","Shot":"*","Dribble":"s","Pressure":"^","Ball Receipt*":"D","Carry":"X"
}
color_dict = {
    "Pass":"blue","Shot":"red","Dribble":"green","Pressure":"orange","Ball Receipt*":"purple","Carry":"brown"
}

fig,ax=plt.subplots(figsize=(8,12))
draw_pitch(ax)
for etype in event_types:
    df_sub = olmo_events[ [is_pass(r.to_dict()) if etype=="Pass" else
                            is_shot(r.to_dict()) if etype=="Shot" else
                            is_dribble(r.to_dict()) if etype=="Dribble" else
                            is_pressure(r.to_dict()) if etype=="Pressure" else
                            is_ballreceipt(r.to_dict()) if etype=="Ball Receipt*" else
                            is_carry(r.to_dict()) for _,r in olmo_events.iterrows()] ]
    if not df_sub.empty:
        xs,ys=[],[]
        for i,row in df_sub.iterrows():
            x,y=extract_xy(row.to_dict())
            xs.append(x); ys.append(y)
        ax.scatter(xs,ys,s=50,marker=marker_dict[etype],color=color_dict[etype],label=etype,alpha=0.6)
ax.set_xlim(0,120); ax.set_ylim(0,80); ax.invert_yaxis(); ax.axis("off")
ax.set_title(f"Dani Olmo — All Event Types (n={len(olmo_events)})")
ax.legend(loc="upper left", bbox_to_anchor=(1.02,1))
plt.tight_layout()
if SAVE_FIGURES: fig.savefig("olmo_all_events.png",dpi=200,bbox_inches="tight")
plt.show()

fig2,ax2=plt.subplots(figsize=(8,12))
draw_pitch(ax2)
if not olmo_xy.empty:
    sns.kdeplot(x=olmo_xy["x"],y=olmo_xy["y"],fill=True,bw_adjust=0.6,thresh=0.05,levels=15,ax=ax2,cmap="Reds")
ax2.set_xlim(0,120); ax2.set_ylim(0,80); ax2.invert_yaxis(); ax2.axis("off")
ax2.set_title("Dani Olmo — Heatmap of Actions")
if SAVE_FIGURES: fig2.savefig("olmo_heatmap.png",dpi=200,bbox_inches="tight")
plt.show()

print(f"Player: {PLAYER_CANONICAL}")
print(f"Matches covered: {olmo_played_match_ids}")
print(f"Total events: {olmo_stats['total_events']}")
for etype in event_types:
    print(f"  {etype}: {olmo_stats[etype]}")
print(f"Goals: {olmo_stats['Goals']}, Assists: {olmo_stats['Assists']}, xG: {olmo_stats['xG']:.2f}")
print("\nComparison with {COMPARE_PLAYERS} other attackers (total events + major actions):")
print(comp_df[["player_name","total_events"]+event_types])
print("\nInterpretation:")
print(" - Scatter plot shows locations of each action type; legend matches markers/colors.")
print(" - Heatmap summarizes where Olmo is most active on the pitch.")

# Find all event types for Olmo
event_types = olmo_events['type'].apply(lambda e: safe_get(e, 'name') if isinstance(e, dict) else None)
print(event_types.value_counts())


# save this as app.py
import streamlit as st
import os, json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import defaultdict

st.set_page_config(layout="wide", page_title="Dani Olmo Analysis — Euro 2024")

# ---------------- CONFIG ----------------
DATA_FOLDER = "/content"  # change to your folder with JSON files
PLAYER_CANONICAL = "Daniel Olmo Carvajal"
COMPARE_PLAYERS = 2

# ---------------- HELPERS ----------------
def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def safe_get(d, *keys, default=None):
    cur = d
    try:
        for k in keys:
            if cur is None:
                return default
            if isinstance(k,int): cur = cur[k]
            else: cur = cur.get(k, default) if isinstance(cur, dict) else default
        return cur
    except Exception:
        return default

def ensure_list(x):
    if x is None: return []
    return x if isinstance(x,list) else [x]

def event_player_name(e):
    return safe_get(e,"player","name") or safe_get(e,"player_name") or safe_get(e,"player","player_name") or ""

def extract_xy(e):
    loc = safe_get(e,"location")
    if isinstance(loc,list) and len(loc)>=2: return float(loc[0]),float(loc[1])
    pos = safe_get(e,"position")
    if isinstance(pos,dict) and "x" in pos and "y" in pos: return float(pos["x"]),float(pos["y"])
    shotloc = safe_get(e,"shot","location")
    if isinstance(shotloc,list) and len(shotloc)>=2: return float(shotloc[0]),float(shotloc[1])
    return np.nan,np.nan

def safe_type(e): return (safe_get(e,"type","name") or "").lower()
def is_pass(e): return "pass" in safe_type(e)
def is_shot(e): return "shot" in safe_type(e)
def is_dribble(e): return "dribble" in safe_type(e)
def is_pressure(e): return "pressure" in safe_type(e)
def is_ballreceipt(e): return "ball receipt" in safe_type(e)
def is_carry(e): return "carry" in safe_type(e)
def shot_is_goal(e): return (safe_get(e,"shot","outcome","name") or "").lower()=="goal"
def pass_is_assist(e):
    p = safe_get(e,"pass")
    return isinstance(p,dict) and ((p.get("goal_assist") or p.get("assist") or p.get("is_assist")) is True)
def get_shot_xg(e):
    xg = safe_get(e,"shot","statsbomb_xg") or safe_get(e,"shot","xg") or safe_get(e,"xg")
    try: return float(xg) if xg is not None else 0.0
    except: return 0.0

event_types = ["Pass","Shot","Dribble","Pressure","Ball Receipt*","Carry"]
marker_dict = {"Pass":"o","Shot":"*","Dribble":"s","Pressure":"^","Ball Receipt*":"D","Carry":"X"}
color_dict = {"Pass":"blue","Shot":"red","Dribble":"green","Pressure":"orange","Ball Receipt*":"purple","Carry":"brown"}

# ---------------- LOAD MATCHES ----------------
matches_file = st.text_input("Path to competitions/matches JSON (e.g., 282.json)", "282.json")
if not os.path.exists(matches_file):
    st.error(f"File {matches_file} not found")
    st.stop()

with open(matches_file,"r",encoding="utf-8") as f:
    matches = json.load(f)

spain_matches = []
for m in matches:
    ht = safe_get(m,"home_team","home_team_name") or safe_get(m,"home_team","name") or ""
    at = safe_get(m,"away_team","away_team_name") or safe_get(m,"away_team","name") or ""
    if (isinstance(ht,str) and ht.lower()=="spain") or (isinstance(at,str) and at.lower()=="spain"):
        spain_matches.append(m)

spain_match_ids = [m["match_id"] for m in spain_matches]
st.write(f"Found {len(spain_matches)} Spain matches: {spain_match_ids}")

# ---------------- LOAD EVENTS ----------------
all_files = os.listdir(DATA_FOLDER)
event_files = [f for f in all_files if f.endswith("_event.json") and any(str(mid) in f for mid in spain_match_ids)]
lineup_files = [f for f in all_files if f.endswith("_lineups.json") and any(str(mid) in f for mid in spain_match_ids)]

all_events=[]
for ef in event_files:
    data = load_json(os.path.join(DATA_FOLDER,ef))
    if isinstance(data,list): all_events.extend(data)
    elif isinstance(data,dict):
        for v in data.values():
            if isinstance(v,list): all_events.extend(v)

events_df = pd.DataFrame(all_events)
if events_df.empty: st.warning("No events loaded")

# ---------------- FILTER PLAYER EVENTS ----------------
player_mask = events_df.apply(lambda r: (event_player_name(r.to_dict()) or "").lower()==PLAYER_CANONICAL.lower(), axis=1)
player_events = events_df[player_mask].copy()
player_events = player_events.reset_index(drop=True)
xs,ys=[],[]
for i,row in player_events.iterrows():
    x,y = extract_xy(row.to_dict())
    xs.append(x); ys.append(y)
player_events["x"]=xs; player_events["y"]=ys
player_xy = player_events.dropna(subset=["x","y"])

# ---------------- COMPUTE STATS ----------------
stats = {"total_events": len(player_events)}
for et in event_types:
    stats[et] = sum(player_events.apply(lambda r: is_pass(r.to_dict()) if et=="Pass" else
                                        is_shot(r.to_dict()) if et=="Shot" else
                                        is_dribble(r.to_dict()) if et=="Dribble" else
                                        is_pressure(r.to_dict()) if et=="Pressure" else
                                        is_ballreceipt(r.to_dict()) if et=="Ball Receipt*" else
                                        is_carry(r.to_dict()), axis=1))
stats["Goals"] = sum(player_events.apply(shot_is_goal, axis=1))
stats["Assists"] = sum(player_events.apply(pass_is_assist, axis=1))
stats["xG"] = sum(player_events.apply(get_shot_xg, axis=1))

st.subheader(f"{PLAYER_CANONICAL} Stats")
st.json(stats)

# ---------------- PLOT FUNCTIONS ----------------
def draw_pitch(ax=None,length=120,width=80,lw=1.2,color="black"):
    if ax is None: ax=plt.gca()
    ax.plot([0,0],[0,width],color=color,linewidth=lw)
    ax.plot([0,length],[width,width],color=color,linewidth=lw)
    ax.plot([length,length],[width,0],color=color,linewidth=lw)
    ax.plot([length,0],[0,0],color=color,linewidth=lw)
    ax.plot([length/2,length/2],[0,width],color=color,linewidth=lw)
    return ax

# ---------------- SCATTER PLOT (#3) ----------------
st.subheader("Detailed Action Scatter Plot (#3)")
fig,ax=plt.subplots(figsize=(6,9))
draw_pitch(ax)
for et in event_types:
    sub_df = player_events[player_events.apply(lambda r: is_pass(r.to_dict()) if et=="Pass" else
                                               is_shot(r.to_dict()) if et=="Shot" else
                                               is_dribble(r.to_dict()) if et=="Dribble" else
                                               is_pressure(r.to_dict()) if et=="Pressure" else
                                               is_ballreceipt(r.to_dict()) if et=="Ball Receipt*" else
                                               is_carry(r.to_dict()), axis=1)]
    if not sub_df.empty:
        ax.scatter(sub_df["x"],sub_df["y"],s=50,marker=marker_dict[et],color=color_dict[et],label=et,alpha=0.6)
ax.set_xlim(0,120); ax.set_ylim(0,80); ax.invert_yaxis(); ax.axis("off")
ax.set_title(f"Dani Olmo — All Event Types (n={len(player_events)})")
ax.legend(loc="upper right", bbox_to_anchor=(1.2,1))
st.pyplot(fig)

# ---------------- HEATMAP (#5) ----------------
st.subheader("Coach-Friendly Heatmap (#5)")
fig2,ax2=plt.subplots(figsize=(6,9))
draw_pitch(ax2)
if not player_xy.empty:
    sns.kdeplot(x=player_xy["x"],y=player_xy["y"],fill=True,bw_adjust=0.6,thresh=0.05,levels=15,ax=ax2,cmap="Reds")
ax2.set_xlim(0,120); ax2.set_ylim(0,80); ax2.invert_yaxis(); ax2.axis("off")
ax2.set_title("Dani Olmo — Heatmap of Actions")
st.pyplot(fig2)

# ---------------- COMPARISON TABLE ----------------
st.subheader("Comparison with Top Spain Attackers")
all_lineups_dict = defaultdict(list)
for lf in lineup_files:
    data = load_json(os.path.join(DATA_FOLDER,lf))
    if isinstance(data,list):
        for entry in data:
            lineup = safe_get(entry,"lineup") or safe_get(entry,"players") or entry
            team_name = safe_get(entry,"team_name") or safe_get(entry,"team","name")
            if team_name and lineup: all_lineups_dict[team_name].extend(ensure_list(lineup))
spain_players = all_lineups_dict.get("Spain",[])
players_info=[]
for p in spain_players:
    pname = safe_get(p,"player_name") or safe_get(p,"player","name") or safe_get(p,"name")
    pid = safe_get(p,"player_id") or safe_get(p,"player","id")
    players_info.append({"player_id":pid,"player_name":pname})
players_df = pd.DataFrame(players_info).drop_duplicates(subset=["player_id","player_name"])

def compute_player_events(player_name):
    mask = events_df.apply(lambda r: (event_player_name(r.to_dict()) or "").lower()==player_name.lower(), axis=1)
    df = events_df[mask]
    stats = {"player_name":player_name,"total_events":len(df)}
    for et in event_types:
        stats[et] = sum(df.apply(lambda r: is_pass(r.to_dict()) if et=="Pass" else
                                        is_shot(r.to_dict()) if et=="Shot" else
                                        is_dribble(r.to_dict()) if et=="Dribble" else
                                        is_pressure(r.to_dict()) if et=="Pressure" else
                                        is_ballreceipt(r.to_dict()) if et=="Ball Receipt*" else
                                        is_carry(r.to_dict()), axis=1))
    return stats

comp_list = [compute_player_events(PLAYER_CANONICAL)]
other_attackers = players_df[players_df["player_name"].str.lower()!=PLAYER_CANONICAL.lower()]["player_name"].values
for pname in other_attackers[:COMPARE_PLAYERS]:
    comp_list.append(compute_player_events(pname))
comp_df = pd.DataFrame(comp_list)
st.dataframe(comp_df[["player_name","total_events"]+event_types])

# ---------------- LAYMAN-FRIENDLY SUMMARY ----------------
st.subheader("Summary for Coaches / Layman")
summary_text = f"""
{PLAYER_CANONICAL} helps move the ball from midfield to attack, works hard to win the ball back,
and is a threat near the opponent's goal with his passes and shots.
He touches the ball a lot, dribbles past players, and is very involved whenever Spain is attacking.
"""
st.write(summary_text)
